// <auto-generated />
using System;
using AttendanceManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttendanceManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260721060335_AddPaidLeaveCarryoverFields")]
    partial class AddPaidLeaveCarryoverFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttendanceManagementSystem.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("ClockInTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("ClockOutTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("LateMinutes")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("LunchBreakEndTimeSnapshot")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("LunchBreakStartTimeSnapshot")
                        .HasColumnType("time");

                    b.Property<int>("OvertimeMinutes")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("ScheduledEndTimeSnapshot")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("ScheduledStartTimeSnapshot")
                        .HasColumnType("time");

                    b.Property<int>("ScheduledWorkMinutesSnapshot")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("SmallBreak1EndTimeSnapshot")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("SmallBreak1StartTimeSnapshot")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("SmallBreak2EndTimeSnapshot")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("SmallBreak2StartTimeSnapshot")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkMinutes")
                        .HasColumnType("int");

                    b.HasKey("AttendanceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Models.AttendanceCorrectionRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("AdminComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan>("AfterTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<int>("AttendanceId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("BeforeTime")
                        .HasColumnType("time");

                    b.Property<string>("CorrectionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RequestId");

                    b.HasIndex("AttendanceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AttendanceCorrectionRequests");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Models.AttendanceStampLog", b =>
                {
                    b.Property<int>("AttendanceStampLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceStampLogId"));

                    b.Property<double?>("AccuracyMeters")
                        .HasColumnType("float");

                    b.Property<int>("AttendanceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("GpsStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StampType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("StampedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("AttendanceStampLogId");

                    b.HasIndex("AttendanceId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StampType");

                    b.HasIndex("StampedAt");

                    b.HasIndex("EmployeeId", "StampedAt");

                    b.ToTable("AttendanceStampLogs");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Models.CompanyCalendarDay", b =>
                {
                    b.Property<int>("CompanyCalendarDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyCalendarDayId"));

                    b.Property<DateTime>("CalendarDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("HolidayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyCalendarDayId");

                    b.HasIndex("CalendarDate")
                        .IsUnique();

                    b.HasIndex("DayType");

                    b.HasIndex("IsWorkingDay");

                    b.HasIndex("CalendarDate", "IsWorkingDay");

                    b.ToTable("CompanyCalendarDays");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastFailedLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEndAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("LunchBreakEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("LunchBreakStartTime")
                        .HasColumnType("time");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("ScheduledEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("ScheduledStartTime")
                        .HasColumnType("time");

                    b.Property<int>("ScheduledWorkMinutes")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("SmallBreak1EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("SmallBreak1StartTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("SmallBreak2EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("SmallBreak2StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Models.MonthlyClosing", b =>
                {
                    b.Property<int>("MonthlyClosingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonthlyClosingId"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ClosedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ClosingComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("ReopenComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReopenedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReopenedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("TargetMonth")
                        .HasColumnType("int");

                    b.Property<int>("TargetYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MonthlyClosingId");

                    b.HasIndex("ClosedByEmployeeId");

                    b.HasIndex("IsClosed");

                    b.HasIndex("ReopenedByEmployeeId");

                    b.HasIndex("TargetYear", "TargetMonth")
                        .IsUnique();

                    b.ToTable("MonthlyClosings");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Models.OperationLog", b =>
                {
                    b.Property<int>("OperationLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperationLogId"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TargetId")
                        .HasColumnType("int");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OperationLogId");

                    b.HasIndex("ActionName");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EmployeeId");

                    b.ToTable("OperationLogs");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Models.PaidLeaveBalance", b =>
                {
                    b.Property<int>("PaidLeaveBalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaidLeaveBalanceId"));

                    b.Property<double>("CarriedOverDays")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CurrentGrantDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CurrentGrantExpiryDate")
                        .HasColumnType("date");

                    b.Property<double>("CurrentGrantedDays")
                        .HasColumnType("float");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<double>("ExpiredDays")
                        .HasColumnType("float");

                    b.Property<double>("GrantedDays")
                        .HasColumnType("float");

                    b.Property<DateTime?>("LastCalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("RemainingDays")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("UsedDays")
                        .HasColumnType("float");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("PaidLeaveBalanceId");

                    b.HasIndex("CurrentGrantDate");

                    b.HasIndex("CurrentGrantExpiryDate");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Year");

                    b.HasIndex("EmployeeId", "Year")
                        .IsUnique();

                    b.ToTable("PaidLeaveBalances");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Models.PaidLeaveGrantHistory", b =>
                {
                    b.Property<int>("PaidLeaveGrantHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaidLeaveGrantHistoryId"));

                    b.Property<DateTime>("AttendanceCheckEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("AttendanceCheckStartDate")
                        .HasColumnType("date");

                    b.Property<double>("AttendanceRate")
                        .HasColumnType("float");

                    b.Property<int>("AttendedDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("GrantDate")
                        .HasColumnType("date");

                    b.Property<string>("GrantStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("GrantedDays")
                        .HasColumnType("float");

                    b.Property<bool>("IsAttendanceRateEnough")
                        .HasColumnType("bit");

                    b.Property<double>("RemainingDays")
                        .HasColumnType("float");

                    b.Property<int>("TotalWorkDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("UsedDays")
                        .HasColumnType("float");

                    b.HasKey("PaidLeaveGrantHistoryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("GrantDate");

                    b.HasIndex("GrantStatus");

                    b.HasIndex("EmployeeId", "GrantDate")
                        .IsUnique();

                    b.ToTable("PaidLeaveGrantHistories");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Models.PaidLeaveRequest", b =>
                {
                    b.Property<int>("PaidLeaveRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaidLeaveRequestId"));

                    b.Property<string>("AdminComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Days")
                        .HasColumnType("float");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LeaveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PaidLeaveRequestId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("PaidLeaveRequests");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Models.Attendance", b =>
                {
                    b.HasOne("AttendanceManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Models.AttendanceCorrectionRequest", b =>
                {
                    b.HasOne("AttendanceManagementSystem.Models.Attendance", "Attendance")
                        .WithMany()
                        .HasForeignKey("AttendanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendanceManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attendance");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Models.AttendanceStampLog", b =>
                {
                    b.HasOne("AttendanceManagementSystem.Models.Attendance", "Attendance")
                        .WithMany()
                        .HasForeignKey("AttendanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AttendanceManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attendance");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Models.Employee", b =>
                {
                    b.HasOne("AttendanceManagementSystem.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Models.MonthlyClosing", b =>
                {
                    b.HasOne("AttendanceManagementSystem.Models.Employee", "ClosedByEmployee")
                        .WithMany()
                        .HasForeignKey("ClosedByEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AttendanceManagementSystem.Models.Employee", "ReopenedByEmployee")
                        .WithMany()
                        .HasForeignKey("ReopenedByEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ClosedByEmployee");

                    b.Navigation("ReopenedByEmployee");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Models.OperationLog", b =>
                {
                    b.HasOne("AttendanceManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Models.PaidLeaveBalance", b =>
                {
                    b.HasOne("AttendanceManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Models.PaidLeaveGrantHistory", b =>
                {
                    b.HasOne("AttendanceManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Models.PaidLeaveRequest", b =>
                {
                    b.HasOne("AttendanceManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AttendanceManagementSystem.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
